---

dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
    options:
      memory: 512
      cpus: 1
platforms:
  - name: ubuntu16
    box: generic/ubuntu1604
  - name: ubuntu18
    box: generic/ubuntu1804
  - name: debian9
    box: debian/stretch64
  - name: debian10
    box: debian/buster64
  - name: centos7
    box: centos/7
  - name: centos8
    box: centos/8
  - name: freebsd11
    box: generic/freebsd11
  - name: freebsd12
    box: generic/freebsd12
provisioner:
  name: ansible
  log: true
  inventory:
    host_vars:
      freebsd11:
        ansible_python_interpreter: "/usr/local/bin/python3"
      freebsd12:
        ansible_python_interpreter: "/usr/local/bin/python3"
verifier:
  name: ansible
