---
dist: bionic

language: python
python:
  - 3.6
services: docker

env:
  global:
    #- ROLE_NAME: ntp
    - VAGRANT_VER: 2.2.7
  matrix:
    - MOLECULE_DISTRO_BOX: generic/ubuntu1604
    - MOLECULE_DISTRO_BOX: generic/ubuntu1804
    - MOLECULE_DISTRO_BOX: debian/stretch64
    - MOLECULE_DISTRO_BOX: debian/buster64
    - MOLECULE_DISTRO_BOX: centos/7
    - MOLECULE_DISTRO_BOX: centos/8
    - MOLECULE_DISTRO_BOX: generic/freebsd11
    - MOLECULE_DISTRO_BOX: generic/freebsd12

install:
  - sudo add-apt-repository universe && sudo apt update
  - wget https://releases.hashicorp.com/vagrant/$VAGRANT_VER/vagrant_"$VAGRANT_VER"_x86_64.deb
  - sudo dpkg -i vagrant_"$VAGRANT_VER"_x86_64.deb
  - sudo apt install qemu-kvm qemu-utils libvirt-bin libvirt0 libvirt-dev
  - vagrant plugin install vagrant-libvirt
  - pip install molecule molecule-vagrant docker python-vagrant paramiko
  - sudo chmod o+rwx /var/run/libvirt/libvirt-sock

    #before_script:
    #  - cd ../
    #  - mv role*$ROLE_NAME $ROLE_NAME
    #  - cd $ROLE_NAME

script:
  # Basic role syntax check
  # - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # Check ansible version
  - ansible --version
  # Check molecule version
  - molecule --version
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
