galaxy_info:
  role_name: ntp
  author: Muhammad Moinur Rahman
  description: ntp installation and configuration for *nix alike OS.
  company: DZCRD Networks Ltd.
  license: license (BSD-3-Clause)
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Debian
      versions:
        - stretch
        - buster
    - name: Ubuntu
      versions:
        - xenial
        - bionic
    - name: FreeBSD
      versions:
        - 11.3
        - 12.1
    - name: HardenedBSD
      versions:
        - all
  galaxy_tags:
    - system
    - ntp
    - date
    - time
    - timezone
dependencies: []
